// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function AutoFetchBoothInfo(arg1:string):Promise<main.BoothInfo>;

export function FetchBoothImageFromURL(arg1:string):Promise<string>;

export function FetchBoothInfoWithGemini(arg1:string):Promise<main.BoothInfo>;

export function GetGeminiApiKey():Promise<string>;

export function GetParentProduct(arg1:string):Promise<db.ProductInfo>;

export function GetProductByPath(arg1:string):Promise<db.ProductInfo>;

export function Greet(arg1:string):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<main.FileItem>>;

export function SaveGeminiApiKey(arg1:string):Promise<void>;

export function UpdateProduct(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;
