// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoFetchBoothInfo(arg1) {
  return window['go']['main']['App']['AutoFetchBoothInfo'](arg1);
}

export function FetchBoothImageFromURL(arg1) {
  return window['go']['main']['App']['FetchBoothImageFromURL'](arg1);
}

export function FetchBoothInfoWithGemini(arg1) {
  return window['go']['main']['App']['FetchBoothInfoWithGemini'](arg1);
}

export function GetGeminiApiKey() {
  return window['go']['main']['App']['GetGeminiApiKey']();
}

export function GetParentProduct(arg1) {
  return window['go']['main']['App']['GetParentProduct'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function SaveGeminiApiKey(arg1) {
  return window['go']['main']['App']['SaveGeminiApiKey'](arg1);
}

export function UpdateProduct(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2, arg3, arg4);
}
